#cloud-config
autoinstall:
  version: 1
  storage:
    layout:
      name: zfs
      match:
        size: largest
      swap:
        size: 20G  # Set our desired swap size
  identity:
    hostname: ubuntu
  early-commands:
    - apt-get install -y zfsutils-linux
  late-commands:
    - zpool set cachefile= rpool
    - cp /etc/zfs/zpool.cache "/target/etc/zfs/"
